name: Deploy file index

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  index-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get file list
      run: |
        echo "Collecting file list..."
        files=$(find . -type f | grep -vE '(^\.\/\.git|^\.\/\.github)' )

        echo "Generating index.json file..."
        echo "[" > index.json
        for file in $files; do
          echo "{" >> index.json
          echo "  \"path\": \"$file\"," >> index.json
          echo "  \"raw_url\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/$file\"" >> index.json
          echo "}," >> index.json
        done
        sed -i '$ s/.$//' index.json
        echo "]" >> index.json

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        git add index.json
        git commit -a -m "Add changes"
        
    - name: Create branch and push index.json
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy
        force: true
